services:
  postgres:
    image: postgres:15.4-alpine3.17
    container_name: postgres-sql-bsn
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: booK_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  bsn-api:
    container_name: bsn-api
    image: bsn/bsn-api:1.0.5
    ports:
      - 8090:8090
    networks:
      - spring-demo
    depends_on:
      - postgres
  bsn-ui:
    image: bsn/bsn-ui:1.0.3
    container_name: bsn-ui
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - 8080:80
    networks:
      - spring-demo
    depends_on:
      - bsn-api

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
