spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  flyway:
    baseline-on-migrate: true
    enabled: true

springdoc:
  default-produces-media-type: application/json

server:
  error:
    include-binding-errors: always
    include-message: always
  servlet:
    context-path: /api/v1/
