spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booK_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${EMAIL_HOSTNAME:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_USERNAME:georgeswakeu21@gmail.com}
    password: ${EMAIL_PASSWORD:qbcoghiyxdhvgpog}
    properties:
      mail:
        smtp:
          auth: true
          port: 25
          ssl:
            enable: true
            trust: "*"
          starttls:
            required: true
            enable: true
        transport:
          protocol: smtp

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 8640000
  cors:
    allowedOrigins: http://localhost:4200,http://localhost:8090
  mailing:
    frontend:
      activation-url: ${MAILING_FRONTEND_ACTIVATION_URL:http://localhost:4200/activate-account}